# Section A – Conceptual Understanding



### A1. Why are NumPy arrays preferred over Python lists?

NumPy arrays are mainly used for numerical calculations because they are faster than normal Python lists. They also take less memory and provide many built-in mathematical functions. Because of this, NumPy is very useful when working with large amounts of data in AI and ML.

### A2. Explain vectorization.

Vectorization means doing an operation on the complete NumPy array instead of using a `for` loop for each value. It makes the code shorter and usually much faster. This is especially useful when we have large datasets because NumPy can process many values at once. 


### A3. Difference between `A * B` and `A @ B`

`A * B` means multiplying the corresponding elements of two arrays. On the other hand, `A @ B` is used for matrix multiplication. In neural networks, `*` can be useful for element-wise operations, while `@` is commonly used to multiply inputs with weights.


### A4. What is broadcasting?

Broadcasting is a feature in NumPy that allows us to perform operations between arrays with different shapes. NumPy automatically adjusts the smaller array when their dimensions are compatible. Two dimensions are compatible when they are equal or when one of them is `1`.
```


### A5. Difference between `flatten()` and `ravel()`

Both `flatten()` and `ravel()` convert an array into a one-dimensional array. `flatten()` usually creates a new copy, while `ravel()` generally tries to use the existing data without making a copy. So, when memory is limited, I would prefer `ravel()` because it can use less extra memory.

### A6. Explain `axis=0` and `axis=1`.

For a 2D array, `axis=0` means performing an operation column-wise, and `axis=1` means performing it row-wise.

For example:

```python
a = np.array([[1, 2],
              [3, 4]])

### A7. Why do we normalize or standardize numerical features?

Normalization and standardization are used to bring numerical features to a similar scale.

| Normalization | Standardization |
|---|---|
| Converts values to a fixed range, usually 0 to 1. | Converts values based on the mean and standard deviation. |
| Uses the minimum and maximum values. | Uses the mean and standard deviation. |
| The values usually stay between 0 and 1. | Values can be negative or positive. |
| Useful when we need a fixed range of values. | Useful when the data has different distributions or scales. |
| Example result: `0.2, 0.5, 0.8` | Example result: `-1.2, 0, 1.3` |
| Commonly called Min-Max scaling. | Commonly called Z-score scaling. |

We use these techniques so that features with different ranges do not affect the ML model unfairly.

### A8. Why is `np.nanmean()` used?

`np.nanmean()` is useful when our data contains missing values represented by `NaN`. It calculates the mean while ignoring the `NaN` values. If we use `np.mean()` directly on data containing `NaN`, the result will normally be `NaN`.



### A9. Shape of a Batch of RGB Images

For normal ML data, the shape is usually represented as `(samples, features)`. For RGB images, we also need height, width, and color channels.

So, 64 RGB images with a size of 128 × 128 have the shape:

```text
(64, 128, 128, 3)
````

Here, `64` is the number of images and `3` represents the RGB channels.

```

:contentReference[oaicite:0]{index=0}
```


### A10. Why is Reproducibility Important?

Reproducibility is important because we should get the same results when we run an experiment again. Random operations can give different results each time. By using `np.random.default_rng(seed)` with a fixed seed, we can get the same random values and make our experiments easier to test and compare.

# Section B – Predict the Output


### B1. Predict the exact output and/or resulting shape. Justify in one sentence

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print((a + b).shape)

#predicted output(3, 3)


(3, 3)


# B2. Predict the output and/or shape

In [ ]:
x = np.arange(1, 7).reshape(2, 3)
print(x[:, 1])


#predicted output [2 5]

[2 5]


# B3. Predict the output and/or shape

In [ ]:
arr = np.array([5, 10, 15, 20, 25])
print(arr[arr % 10 == 0])


#predicted output[10 20]

[10 20]


# B4. Predict the output and/or shape

In [ ]:
m = np.array([[1, 2], [3, 4]])
print(m.T @ m)


#predicted output [[10 14]
#                  [14 20]]

[[10 14]
 [14 20]]


# B5. Predict the output and/or shape

In [ ]:
data = np.array([1, 2, np.nan, 4])
print(np.mean(data), np.nanmean(data))

#predicted output  nan 2.3333333333333335


nan 2.3333333333333335


# B6. Predict the output and/or shape

In [ ]:
x = np.array([10, 20, 30])
y = np.where(x > 15, 1, 0)
print(y)

#predicted output [0 1 1]


[0 1 1]


# B7. Predict the output and/or shape. 

In [ ]:
a = np.zeros((3, 4))
print(a.ndim, a.size)


#predicted output 2 12


2 12


# B8. Predict the output and/or shape

In [ ]:
arr = np.arange(1, 13).reshape(3, 4)
print(arr[::-1, ::-1])


#predicted output [[12 11 10  9]
#                  [ 8  7  6  5]
#                  [ 4  3  2  1]]

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


# Section C – Coding / Implementation


#### C1. Given a 1D NumPy array of exam scores, use np.where() to produce labels 'P' (score >= 40) or 'F' (score < 40). 

In [10]:

import numpy as np

scores = np.array([35, 45, 60, 25, 80])

result = np.where(scores >= 40, 'P', 'F')

print(result)

['F' 'P' 'P' 'F' 'P']


#### C2. Write a function standardize(x) that takes a 1D NumPy array and returns its z-score standardized version using only NumPy

In [11]:

import numpy as np

def standardize(x):
    return (x - np.mean(x)) / np.std(x)

x = np.array([10, 20, 30, 40, 50])

print(standardize(x))

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


##### C3. Given two 2D NumPy arrays representing separate batches with the same number of features, combine them using an appropriate NumPy stacking function and print the resulting shape

In [12]:

import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[7, 8, 9],
              [10, 11, 12]])

result = np.vstack((a, b))

print(result)
print(result.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


##### C4. Given X with shape (100, 5), compute column-wise mean and standard deviation and standardize the matrix in one vectorized expression

In [13]:

import numpy as np

X = np.random.rand(100, 5)

mean = X.mean(axis=0)
std = X.std(axis=0)

X_standardized = (X - mean) / std

print(X_standardized.shape)

(100, 5)


#### C5. Implement y_pred = X @ w + b for a feature matrix X, weight vector w and bias b. Then compute MSE using y_true

In [14]:

import numpy as np

X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

w = np.array([0.5, 1.0])
b = 2

y_true = np.array([4, 6, 8])

y_pred = X @ w + b

mse = np.mean((y_true - y_pred) ** 2)

print(y_pred)
print(mse)

[4.5 6.  7.5]
0.16666666666666666


##### C6. Using np.random.default_rng() with a fixed seed, generate 10 samples and 3 features from a normal distribution. Print the shape and confirm identical results with the same seed. 

In [15]:

import numpy as np

rng1 = np.random.default_rng(42)
x1 = rng1.normal(size=(10, 3))

rng2 = np.random.default_rng(42)
x2 = rng2.normal(size=(10, 3))

print(x1.shape)
print(np.array_equal(x1, x2))

(10, 3)
True


##### C7. Given a grayscale image as a 2D NumPy array with pixel values in [0, 255], normalize the values to [0, 1] using min-max normalization

In [16]:

import numpy as np

image = np.array([[0, 50],
                  [100, 255]])

normalized = (image - image.min()) / (image.max() - image.min())

print(normalized)

[[0.         0.19607843]
 [0.39215686 1.        ]]


##### C8. Given 4 RGB images of shape (28, 28, 3), stored as shape (4, 28, 28, 3), compute the average pixel value of each image across height, width and channels. State the axis argument and why

In [17]:

import numpy as np

images = np.random.randint(0, 256, (4, 28, 28, 3))

average = images.mean(axis=(1, 2, 3))

print(average.shape)
print(average)

(4,)
[127.3664966  129.46853741 125.93920068 126.1079932 ]


# Section D – Applied / Scenario-Based Problems


#### D1. Data Preprocessing Pipeline
- You are given a raw 1D or 2D NumPy array containing NaN values.
- Describe, step by step, the NumPy operations you would apply to:
- (a) detect missing values,
- (b) handle them appropriately and justify your strategy, and
- (c) normalize or standardize the clean data before it is fed to a model.

Implement the full pipeline in code on a sample array of your own choosing, including at least one NaN.

#### D1. Data Preprocessing Pipeline

A data preprocessing pipeline is used to prepare raw data before it is given to a machine learning model.

### Step 1: Detect Missing Values

First, `np.isnan()` can be used to identify missing values in the NumPy array. It returns `True` for positions containing `NaN` and `False` for other values.

### Step 2: Handle Missing Values

After detecting the missing values, they need to be handled appropriately. In this example, the `NaN` values are replaced with the mean of the available values using `np.nanmean()`. This keeps all the data points instead of removing them.

### Step 3: Standardize the Clean Data

After handling the missing values, the clean data is standardized using its mean and standard deviation. Standardization changes the data so that it is centered around 0 and has a standard deviation of 1.

The complete preprocessing pipeline is:
1. Detect the missing values.
2. Calculate the mean while ignoring `NaN`.
3. Replace the `NaN` values with the mean.
4. Standardize the cleaned data.

In [18]:
import numpy as np

# Sample 1D array containing NaN values
data = np.array([10, 20, np.nan, 40, 50, np.nan])

# Step 1: Detect missing values
missing_values = np.isnan(data)

print("Missing values:")
print(missing_values)

# Step 2: Calculate mean ignoring NaN values
mean_value = np.nanmean(data)

# Replace NaN values with the mean
clean_data = np.where(np.isnan(data), mean_value, data)

print("\nMean used for replacement:", mean_value)
print("Clean data:")
print(clean_data)

# Step 3: Standardize the clean data
mean = np.mean(clean_data)
std = np.std(clean_data)

standardized_data = (clean_data - mean) / std

print("\nStandardized data:")
print(standardized_data)

Missing values:
[False False  True False False  True]

Mean used for replacement: 30.0
Clean data:
[10. 20. 30. 40. 50. 30.]

Standardized data:
[-1.54919334 -0.77459667  0.          0.77459667  1.54919334  0.        ]


# D2. Image Batch Understanding

# Explain, with correct NumPy shapes, how a single RGB image differs from a batch of RGB images

#### A single RGB image is represented using three dimensions: **height, width, and color channels**. For example, if an RGB image is 64 × 64 pixels, its NumPy shape will be:

`(64, 64, 3)`

Here, the first `64` is the height, the second `64` is the width, and `3` represents the RGB channels.

When we have many RGB images, we store them together as a batch. In this case, one extra dimension is added at the beginning to represent the number of images. For example, a batch of 16 RGB images, each of size 64 × 64, will have the shape:

`(16, 64, 64, 3)`

Here, `16` is the number of images, `64` is the height, `64` is the width, and `3` represents the RGB channels.

### Shape Comparison

| Type | NumPy Shape | Meaning |
|---|---|---|
| Single RGB image | `(64, 64, 3)` | Height × Width × RGB channels |
| Batch of 16 RGB images | `(16, 64, 64, 3)` | Number of images × Height × Width × RGB channels |

So, the main difference is that a **single RGB image has 3 dimensions**, while a **batch of RGB images has 4 dimensions**. The extra first dimension tells us how many images are present in the batch.

In [19]:
import numpy as np

# Create a single RGB image of size 64 × 64
single_image = np.random.default_rng(42).integers(
    0, 256, size=(64, 64, 3)
)

# Create a batch of 16 RGB images
image_batch = np.random.default_rng(42).integers(
    0, 256, size=(16, 64, 64, 3)
)

print("Single RGB image shape:", single_image.shape)
print("Batch of RGB images shape:", image_batch.shape)

Single RGB image shape: (64, 64, 3)
Batch of RGB images shape: (16, 64, 64, 3)


### 2. Create a Dummy Batch of 16 Images

Create a batch of 16 RGB images of size 64 × 64 using random pixel values.

In [20]:
import numpy as np

images = np.random.randint(0, 256, (16, 64, 64, 3))

print(images.shape)

(16, 64, 64, 3)


### 3. Compute the Average Image

Compute the element-wise mean across all 16 images using `axis=0`.

In [22]:
average_image = np.mean(images, axis=0)

print(average_image.shape)

(64, 64, 3)


### 4. Shape of the Average Image

The shape of the average image is `(64, 64, 3)`.

The original batch has the shape `(16, 64, 64, 3)`. Using `axis=0` calculates the mean across all 16 images, so the image count dimension is removed. Therefore, the result contains the height, width, and RGB channels.

In [24]:
# Check the shape of the average image
print("Average image shape:", average_image.shape)

# Display the result
print("The average image has 64 × 64 pixels and 3 RGB channels.")

Average image shape: (64, 64, 3)
The average image has 64 × 64 pixels and 3 RGB channels.


# D3. Debug the Model Code 

The following code contains more than one bug:

```python
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])  # shape (3, 2)

w = np.array([0.5, 1.0, 0.2])  # intended weight vector

b = 2.0

y_pred = X @ w + b

y_true = np.array([10, 20, 30])

mse = np.mean(y_true - y_pred ** 2)
```

### Tasks

1. Identify every bug.

2. Explain, in terms of **shapes**, why each bug is a problem.

3. Explain how **operator precedence** affects the MSE calculation.

4. Rewrite the **corrected code**.

1.The given code contains more than one bug. The main problems are the shape of the weight vector and the calculation of MSE.

### 1. Identify Every Bug

### Bug 1: Incorrect shape of the weight vector

The feature matrix `X` has the shape `(3, 2)`. This means there are 3 samples and 2 features in each sample.

The given weight vector is:

```python
w = np.array([0.5, 1.0, 0.2])

### 2. Explain, in terms of shapes, why each bug is a problem.

The feature matrix `X` has the shape `(3, 2)`. This means there are **3 samples** and **2 features** in each sample.

The original weight vector `w` has the shape `(3,)`, because it contains three values:

```python
w = np.array([0.5, 1.0, 0.2])

### 3. Explain how operator precedence affects the MSE calculation.

The original MSE expression is:
The problem is that the exponentiation operator ** has higher precedence than the subtraction operator
```python
mse = np.mean(y_true - (y_pred ** 2))
This is incorrect because MSE requires us to first calculate the difference between the actual and predicted values, then square that difference.

In [25]:
import numpy as np

X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

# X has 2 features, so w should have 2 values
w = np.array([0.5, 1.0])

b = 2.0

# Calculate predicted values
y_pred = X @ w + b

# Actual values
y_true = np.array([10, 20, 30])

# Calculate MSE
mse = np.mean((y_true - y_pred) ** 2)

print("Predicted values:", y_pred)
print("MSE:", mse)




Predicted values: [4.5 6.  7.5]
MSE: 244.16666666666666


# E1. Per-Column Min–Max Normalization 

### E1. Per-Column Min-Max Normalization

In [26]:
import numpy as np

X = np.array([[10, 100],
              [20, 200],
              [30, 300],
              [40, 400]], dtype=float)

min_val = X.min(axis=0)
max_val = X.max(axis=0)

normalized = (X - min_val) / (max_val - min_val)

print(normalized)

[[0.         0.        ]
 [0.33333333 0.33333333]
 [0.66666667 0.66666667]
 [1.         1.        ]]


### Explanation

First, we import NumPy using `import numpy as np`.

Then, we create a 2D array `X` with 4 rows and 2 columns. 
Here, each column represents a feature.

`X.min(axis=0)` finds the minimum value from each column.

`X.max(axis=0)` finds the maximum value from each column.

Next, we use the Min-Max Normalization formula:

**Normalized value = (X - minimum) / (maximum - minimum)**

The normalization is done column-wise because we use `axis=0`.

After normalization, all the values are converted into a range between `0` and `1`.

Finally, `print(normalized)` displays the normalized values.

The minimum value in each column becomes `0`, and the maximum value becomes `1`.

### E2. Three-Level Score Classification

In [27]:
import numpy as np

scores = np.array([25, 40, 55, 70, 85, 95])

result = np.where(scores < 40, "Fail",
                  np.where(scores <= 70, "Average", "Excellent"))

print(result)

['Fail' 'Average' 'Average' 'Average' 'Excellent' 'Excellent']


### Explanation

First, we import NumPy using `import numpy as np`.

Then, we create a NumPy array called `scores` with different student marks.

We use `np.where()` to classify the marks into three categories:

- If the score is less than `40`, it is classified as **Fail**.
- If the score is between `40` and `70`, it is classified as **Average**.
- If the score is greater than `70`, it is classified as **Excellent**.

The second `np.where()` is used inside the first one to check the remaining scores.

Finally, `print(result)` displays the classification for each score.

### Output

['Fail' 'Average' 'Average' 'Average' 'Excellent' 'Excellent']

So, the scores are classified without using any `if-else` statements or loops.